export enum EServiceActions {
  ADD_SERVICE_CATEGORY = '[Service] Add Category',
  ADD_SERVICE_CATEGORY_SUCCESS = '[Service] Add Category Success',
  SEARCH_SERVICE_CATEGORIES = '[Service] Search Categories',
  SEARCH_SERVICE_CATEGORIES_SUCCESS = '[Service] Search Categories Success',
  SEARCH_SERVICE = '[Service] Search',
  SEARCH_SERVICE_SUCCESS = '[Service] Search Success',
  ADD_SERVICE = '[Service] Add Employee',
  ADD_SERVICE_SUCCESS = '[Service] Add Employee Success',
  UPDATE_SERVICE = '[Service] Update Employee',
  UPDATE_SERVICE_SUCCESS = '[Service] Update Employee Success',
  ADD_PRICE_LIST = '[Service] Add Price List',
  ADD_PRICE_LIST_SUCCESS = '[Service] Add Price List Success',
  SEARCH_PRICE_LIST = '[Service] Search Price List',
  SEARCH_PRICE_LIST_SUCCESS = '[Service] Search Price List Success',
}
