export enum EEmployeeActions {
    ADD_EMPLOYEE_CATEGORY = '[Employee] Add Category',
    ADD_EMPLOYEE_CATEGORY_SUCCESS = '[Employee] Add Category Success',
    SEARCH_EMPLOYEE_CATEGORIES = '[Employee] Search Categories',
    SEARCH_EMPLOYEE_CATEGORIES_SUCCESS = '[Employee] Search Categories Success',
    SEARCH_EMPLOYEE = '[Employee] Search',
    SEARCH_EMPLOYEE_SUCCESS = '[Employee] Search Success',
    ADD_EMPLOYEE = '[Employee] Add Employee',
    ADD_EMPLOYEE_SUCCESS = '[Employee] Add Employee Success',
    UPDATE_EMPLOYEE = '[Employee] Update Employee',
    UPDATE_EMPLOYEE_SUCCESS = '[Employee] Update Employee Success',
    ADD_WORK_PLANNER = '[Employee] Add Work Planner',
    ADD_WORK_PLANNER_SUCCESS = '[Employee] Add Work Planner Success',
    SEARCH_USERS = '[Employee] Search Users',
    SEARCH_USERS_SUCCESS = '[Employee] Search Users Success',
}
